//! Embeds the built room UI into the binary so a downloaded executable is a single
//! self-contained file, with nothing to unzip and no folder to keep beside it.
//!
//! `npm run build:room-ui` writes those files into `self-host-dist/`, which is
//! gitignored and absent on a fresh clone. Rather than fail the build, a missing
//! asset is embedded as empty and the relay falls back to reading `self-host-dist/`
//! from disk at runtime — so `cargo build`, `cargo clippy` and the Rust unit tests
//! keep working before the UI has ever been built.

use std::{env, fs, path::PathBuf};

const ASSETS: [&str; 8] = [
    "app.js",
    "app.css",
    "e2ee-worker.js",
    "favicon.svg",
    "apple-touch-icon.png",
    "icon-192.png",
    "icon-512.png",
    "manifest.webmanifest",
];

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let ui_dir = manifest_dir
        .parent()
        .expect("workspace root")
        .join("self-host-dist");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));

    println!("cargo:rerun-if-changed={}", ui_dir.display());

    let mut generated = String::from(
        "// @generated by build.rs — do not edit.\npub static EMBEDDED_UI: &[(&str, &[u8])] = &[\n",
    );

    for name in ASSETS {
        let source = ui_dir.join(name);
        println!("cargo:rerun-if-changed={}", source.display());

        // Copy into OUT_DIR so include_bytes! never points outside the build
        // directory, and so a later UI rebuild reliably retriggers this script.
        let staged = out_dir.join(name);
        let bytes = fs::read(&source).unwrap_or_default();
        fs::write(&staged, &bytes).expect("stage embedded asset");

        generated.push_str(&format!(
            "    ({name:?}, include_bytes!({:?})),\n",
            staged.to_str().expect("utf-8 path")
        ));
    }

    generated.push_str("];\n");
    fs::write(out_dir.join("embedded_ui.rs"), generated).expect("write embedded ui table");
}
